export const CREATE_DOCTOR_REQUEST ='CREATE_DOCTOR_REQUEST'
export const CREATE_DOCTOR_SUCCESS ='CREATE_DOCTOR_SUCCESS'
export const CREATE_DOCTOR_FAIL ='CREATE_DOCTOR_FAIL'
export const CREATE_DOCTOR_RESET='CREATE_DOCTOR_RESET'