


export const UPLOAD_DIET_CHART_REQUEST ='UPLOAD_DIET_CHART_REQUEST'
export const UPLOAD_DIET_CHART_SUCCESS ='UPLOAD_DIET_CHART_SUCCESS'
export const UPLOAD_DIET_CHART_FAIL ='UPLOAD_DIET_CHART_FAIL'
export const UPLOAD_DIET_CHART_RESET='UPLOAD_DIET_CHART_RESET'


export const CREATE_FORM_REQUEST ='CREATE_FORM_REQUEST'
export const CREATE_FORM_SUCCESS ='CREATE_FORM_SUCCESS'
export const CREATE_FORM_FAIL ='CREATE_FORM_FAIL'
export const CREATE_FORM_RESET='CREATE_FORM_RESET'

export const CREATE_PRESC_REQUEST ='CREATE_PRESC_REQUEST'
export const CREATE_PRESC_SUCCESS ='CREATE_PRESC_SUCCESS'
export const CREATE_PRESC_FAIL ='CREATE_PRESC_FAIL'
export const CREATE_PRESC_RESET='CREATE_PRESC_RESET'

export const GET_DOCTOR_PROFILE_REQUEST ='GET_DOCTOR_PROFILE_REQUEST'
export const GET_DOCTOR_PROFILE_SUCCESS ='GET_DOCTOR_PROFILE_SUCCESS'
export const GET_DOCTOR_PROFILE_FAIL ='GET_DOCTOR_PROFILE_FAIL'

export const UPDATE_PATIENT_REQUEST ='UPDATE_PATIENT_REQUEST'
export const UPDATE_PATIENT_SUCCESS ='UPDATE_PATIENT_SUCCESS'
export const UPDATE_PATIENT_FAIL ='UPDATE_PATIENT_FAIL'
export const UPDATE_PATIENT_RESET ='UPDATE_PATIENT_RESET'

export const GET_APPOINTMENT_WITH_DATE_REQUEST ='GET_APPOINTMENT_WITH_DATE_REQUEST'
export const GET_APPOINTMENT_WITH_DATE_SUCCESS ='GET_APPOINTMENT_WITH_DATE_SUCCESS'
export const GET_APPOINTMENT_WITH_DATE_FAIL ='GET_APPOINTMENT_WITH_DATE_FAIL'