export const GOOGLE_SIGNIN_REQUEST ='GOOGLE_SIGNIN_REQUEST'
export const GOOGLE_SIGNIN_SUCCESS ='GOOGLE_SIGNIN_SUCCESS'
export const GOOGLE_SIGNIN_FAIL ='GOOGLE_SIGNIN_FAIL'


export const UPLOAD_DIET_CHART_REQUEST ='UPLOAD_DIET_CHART_REQUEST'
export const UPLOAD_DIET_CHART_SUCCESS ='UPLOAD_DIET_CHART_SUCCESS'
export const UPLOAD_DIET_CHART_FAIL ='UPLOAD_DIET_CHART_FAIL'
export const UPLOAD_DIET_CHART_RESET='UPLOAD_DIET_CHART_RESET'