// export const Url = 'https://mydoctor-app.herokuapp.com/api/v1'
// export const Url = 'https://doctor-app-backend-production.up.railway.app/api/v1'
export const Url='https://doctor-app-backend-production-ffc1.up.railway.app/api/v1'


export const REGISTER_USER_REQUEST ='REGISTER_USER_REQUEST'
export const REGISTER_USER_SUCCESS ='REGISTER_USER_SUCCESS'
export const REGISTER_USER_FAIL ='REGISTER_USER_FAIL'

export const ENROLMENT_PATIENT_REQUEST ='ENROLMENT_PATIENT_REQUEST'
export const ENROLMENT_PATIENT_SUCCESS ='ENROLMENT_PATIENT_SUCCESS'
export const ENROLMENT_PATIENT_FAIL ='ENROLMENT_PATIENT_FAIL'
export const ENROLMENT_PATIENT_RESET ='ENROLMENT_PATIENT_RESET'

export const GET_ALL_PATIENT_REQUEST ='GET_ALL_PATIENT_REQUEST'
export const GET_ALL_PATIENT_SUCCESS ='GET_ALL_PATIENT_SUCCESS'
export const GET_ALL_PATIENT_FAIL ='GET_ALL_PATIENT_FAIL'

export const GET_PATIENT_DETAILS_REQUEST ='GET_PATIENT_DETAILS_REQUEST'
export const GET_PATIENT_DETAILS_SUCCESS ='GET_PATIENT_DETAILS_SUCCESS'
export const GET_PATIENT_DETAILS_FAIL ='GET_PATIENT_DETAILS_FAIL'


export const GET_ALL_PATIENT_FORMS_REQUEST ='GET_ALL_PATIENT_FORMS_REQUEST'
export const GET_ALL_PATIENT_FORMS_SUCCESS ='GET_ALL_PATIENT_FORMS_SUCCESS'
export const GET_ALL_PATIENT_FORMS_FAIL ='GET_ALL_PATIENT_FORMS_FAIL'

export const CREATE_APPOINTMENT_REQUEST ='CREATE_APPOINTMENT_REQUEST'
export const CREATE_APPOINTMENT_SUCCESS ='CREATE_APPOINTMENT_SUCCESS'
export const CREATE_APPOINTMENT_FAIL ='CREATE_APPOINTMENT_FAIL'
export const CREATE_APPOINTMENT_RESET ='CREATE_APPOINTMENT_RESET'


export const GET_APPOINTMENT_REQUEST ='GET_APPOINTMENT_REQUEST'
export const GET_APPOINTMENT_SUCCESS ='GET_APPOINTMENT_SUCCESS'
export const GET_APPOINTMENT_FAIL ='GET_APPOINTMENT_FAIL'

export const PATIENT_LOGIN_REQUEST ='PATIENT_LOGIN_REQUEST'
export const PATIENT_LOGIN_SUCCESS ='PATIENT_LOGIN_SUCCESS'
export const PATIENT_LOGIN_FAIL ='PATIENT_LOGIN_FAIL'

export const SENDOTP_REQUEST ='SENDOTP_REQUEST'
export const SENDOTP_SUCCESS ='SENDOTP_SUCCESS'
export const SENDOTP_FAIL ='SENDOTP_FAIL'
export const SENDOTP_RESET ='SENDOTP_RESET'


export const GET_PRESCRIPTION_REQUEST ='GET_PRESCRIPTION_REQUEST'
export const GET_PRESCRIPTION_SUCCESS ='GET_PRESCRIPTION_SUCCESS'
export const GET_PRESCRIPTIONT_FAIL ='GET_PRESCRIPTION_FAIL'